import type { Room, BookingEvent, Subscription, SystemHealth, DashboardMetrics, AIInsight } from "./types"

export const rooms: Room[] = [
  {
    id: "room-1",
    roomUpn: "cambridge-conf-01@aditumbio.com",
    site: "Cambridge",
    displayName: "Cambridge Boardroom A",
    capacity: 12,
    avProfile: "Teams Room + dual display + HDMI ingest",
    accessNotes: "Reception badge required after 6 PM",
    floor: "3rd Floor",
    building: "Main Campus",
    isActive: true,
  },
  {
    id: "room-2",
    roomUpn: "cambridge-conf-02@aditumbio.com",
    site: "Cambridge",
    displayName: "Cambridge Focus Room B",
    capacity: 6,
    avProfile: "Teams Room + single display",
    accessNotes: "Badge access required",
    floor: "2nd Floor",
    building: "Main Campus",
    isActive: true,
  },
  {
    id: "room-3",
    roomUpn: "cambridge-conf-03@aditumbio.com",
    site: "Cambridge",
    displayName: "Cambridge Executive Suite",
    capacity: 20,
    avProfile: "Premium AV + video wall + wireless presentation",
    accessNotes: "EA approval required for external guests",
    floor: "5th Floor",
    building: "Main Campus",
    isActive: true,
  },
  {
    id: "room-4",
    roomUpn: "oakland-harbor-01@aditumbio.com",
    site: "Oakland",
    displayName: "Oakland Harbor Room",
    capacity: 10,
    avProfile: "Teams Room + display + whiteboard camera",
    accessNotes: "Building access via lobby security",
    floor: "4th Floor",
    building: "West Tower",
    isActive: true,
  },
  {
    id: "room-5",
    roomUpn: "oakland-collab-01@aditumbio.com",
    site: "Oakland",
    displayName: "Oakland Collaboration Space",
    capacity: 8,
    avProfile: "Teams Room + dual display + Surface Hub",
    accessNotes: "Open access during business hours",
    floor: "3rd Floor",
    building: "West Tower",
    isActive: true,
  },
  {
    id: "room-6",
    roomUpn: "oakland-training-01@aditumbio.com",
    site: "Oakland",
    displayName: "Oakland Training Center",
    capacity: 30,
    avProfile: "Full AV suite + recording capability + webinar setup",
    accessNotes: "Advanced booking required for external events",
    floor: "1st Floor",
    building: "East Wing",
    isActive: false,
  },
]

export const bookingEvents: BookingEvent[] = [
  {
    id: "evt-1",
    roomId: "room-1",
    roomName: "Cambridge Boardroom A",
    site: "Cambridge",
    organizer: "Sarah Chen",
    organizerEmail: "sarah.chen@aditumbio.com",
    subject: "Q1 Strategy Review",
    startTime: "2026-03-26T09:00:00Z",
    endTime: "2026-03-26T11:00:00Z",
    outcome: "accepted",
    notificationSent: true,
    notificationTime: "2026-03-26T08:45:12Z",
    createdAt: "2026-03-25T14:30:00Z",
  },
  {
    id: "evt-2",
    roomId: "room-3",
    roomName: "Cambridge Executive Suite",
    site: "Cambridge",
    organizer: "Michael Torres",
    organizerEmail: "m.torres@aditumbio.com",
    subject: "Board Meeting - Quarterly Update",
    startTime: "2026-03-26T14:00:00Z",
    endTime: "2026-03-26T17:00:00Z",
    outcome: "accepted",
    notificationSent: true,
    notificationTime: "2026-03-26T13:45:08Z",
    createdAt: "2026-03-24T09:15:00Z",
  },
  {
    id: "evt-3",
    roomId: "room-1",
    roomName: "Cambridge Boardroom A",
    site: "Cambridge",
    organizer: "Emily Watson",
    organizerEmail: "e.watson@aditumbio.com",
    subject: "Team Sync",
    startTime: "2026-03-26T10:00:00Z",
    endTime: "2026-03-26T11:00:00Z",
    outcome: "declined-conflict",
    declineReason: "Overlapping with existing booking: Q1 Strategy Review",
    notificationSent: true,
    notificationTime: "2026-03-26T08:46:22Z",
    createdAt: "2026-03-26T08:30:00Z",
  },
  {
    id: "evt-4",
    roomId: "room-4",
    roomName: "Oakland Harbor Room",
    site: "Oakland",
    organizer: "James Park",
    organizerEmail: "j.park@aditumbio.com",
    subject: "Product Demo - External Client",
    startTime: "2026-03-26T15:00:00Z",
    endTime: "2026-03-26T16:30:00Z",
    outcome: "accepted",
    notificationSent: true,
    notificationTime: "2026-03-26T14:45:33Z",
    createdAt: "2026-03-25T16:00:00Z",
  },
  {
    id: "evt-5",
    roomId: "room-5",
    roomName: "Oakland Collaboration Space",
    site: "Oakland",
    organizer: "Lisa Kumar",
    organizerEmail: "l.kumar@aditumbio.com",
    subject: "Design Sprint Planning",
    startTime: "2026-03-26T11:00:00Z",
    endTime: "2026-03-26T12:30:00Z",
    outcome: "accepted",
    notificationSent: true,
    notificationTime: "2026-03-26T10:45:19Z",
    createdAt: "2026-03-25T11:20:00Z",
  },
  {
    id: "evt-6",
    roomId: "room-6",
    roomName: "Oakland Training Center",
    site: "Oakland",
    organizer: "Robert Kim",
    organizerEmail: "r.kim@aditumbio.com",
    subject: "New Hire Orientation",
    startTime: "2026-03-27T09:00:00Z",
    endTime: "2026-03-27T12:00:00Z",
    outcome: "declined-policy",
    declineReason: "Room currently under maintenance - available from April 1st",
    notificationSent: true,
    notificationTime: "2026-03-26T09:12:45Z",
    createdAt: "2026-03-26T09:00:00Z",
  },
  {
    id: "evt-7",
    roomId: "room-2",
    roomName: "Cambridge Focus Room B",
    site: "Cambridge",
    organizer: "Anna Schmidt",
    organizerEmail: "a.schmidt@aditumbio.com",
    subject: "1:1 with Manager",
    startTime: "2026-03-26T16:00:00Z",
    endTime: "2026-03-26T16:30:00Z",
    outcome: "pending",
    notificationSent: false,
    createdAt: "2026-03-26T15:50:00Z",
  },
  {
    id: "evt-8",
    roomId: "room-4",
    roomName: "Oakland Harbor Room",
    site: "Oakland",
    organizer: "David Lee",
    organizerEmail: "d.lee@aditumbio.com",
    subject: "Weekly Team Standup",
    startTime: "2026-03-26T09:00:00Z",
    endTime: "2026-03-26T09:30:00Z",
    outcome: "canceled",
    notificationSent: true,
    notificationTime: "2026-03-26T08:55:00Z",
    createdAt: "2026-03-23T10:00:00Z",
  },
]

export const subscriptions: Subscription[] = [
  {
    id: "sub-1",
    roomUpn: "cambridge-conf-01@aditumbio.com",
    roomName: "Cambridge Boardroom A",
    expirationDateTime: "2026-03-28T12:00:00Z",
    status: "active",
    lastNotification: "2026-03-26T08:46:22Z",
  },
  {
    id: "sub-2",
    roomUpn: "cambridge-conf-02@aditumbio.com",
    roomName: "Cambridge Focus Room B",
    expirationDateTime: "2026-03-28T12:00:00Z",
    status: "active",
    lastNotification: "2026-03-26T07:30:00Z",
  },
  {
    id: "sub-3",
    roomUpn: "cambridge-conf-03@aditumbio.com",
    roomName: "Cambridge Executive Suite",
    expirationDateTime: "2026-03-28T12:00:00Z",
    status: "active",
    lastNotification: "2026-03-26T13:45:08Z",
  },
  {
    id: "sub-4",
    roomUpn: "oakland-harbor-01@aditumbio.com",
    roomName: "Oakland Harbor Room",
    expirationDateTime: "2026-03-27T06:00:00Z",
    status: "expiring",
    lastNotification: "2026-03-26T14:45:33Z",
  },
  {
    id: "sub-5",
    roomUpn: "oakland-collab-01@aditumbio.com",
    roomName: "Oakland Collaboration Space",
    expirationDateTime: "2026-03-28T12:00:00Z",
    status: "active",
    lastNotification: "2026-03-26T10:45:19Z",
  },
  {
    id: "sub-6",
    roomUpn: "oakland-training-01@aditumbio.com",
    roomName: "Oakland Training Center",
    expirationDateTime: "2026-03-25T12:00:00Z",
    status: "expired",
    lastNotification: "2026-03-24T16:00:00Z",
  },
]

export const systemHealth: SystemHealth = {
  webhookStatus: "healthy",
  queueDepth: 3,
  deadLetterCount: 0,
  subscriptionHealth: 83,
  lastProcessedTime: "2026-03-26T15:58:42Z",
  notificationSuccessRate: 98.5,
}

export const dashboardMetrics: DashboardMetrics = {
  totalBookingsToday: 24,
  acceptedToday: 19,
  declinedToday: 4,
  notificationsSent: 23,
  avgProcessingTime: 1.2,
}

export const aiInsights: AIInsight[] = [
  {
    id: "insight-1",
    type: "alternative",
    title: "Alternative Room Suggested",
    description: "For Emily Watson's declined booking, Cambridge Focus Room B is available during the same time slot with similar AV capabilities.",
    timestamp: "2026-03-26T08:46:30Z",
    roomId: "room-2",
    severity: "info",
  },
  {
    id: "insight-2",
    type: "anomaly",
    title: "High Decline Rate Detected",
    description: "Cambridge Boardroom A has seen a 40% increase in booking conflicts this week. Consider reviewing scheduling patterns or adding capacity.",
    timestamp: "2026-03-26T12:00:00Z",
    roomId: "room-1",
    severity: "warning",
  },
  {
    id: "insight-3",
    type: "recommendation",
    title: "Subscription Renewal Required",
    description: "Oakland Harbor Room subscription expires in less than 24 hours. Automatic renewal scheduled for 2026-03-27T05:00:00Z.",
    timestamp: "2026-03-26T15:00:00Z",
    severity: "warning",
  },
  {
    id: "insight-4",
    type: "anomaly",
    title: "Webhook Processing Delay",
    description: "Average processing time increased to 2.8s during peak hours (9-10 AM). Queue scaling may be required.",
    timestamp: "2026-03-26T10:15:00Z",
    severity: "info",
  },
]
